# Generated by Django 2.1.3 on 2018-11-27 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancle_Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('cust_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Check_Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.IntegerField()),
                ('check_In', models.DateField()),
                ('check_Out', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Display',
            fields=[
                ('user_name', models.CharField(max_length=50)),
                ('cust_id', models.IntegerField()),
                ('room_type', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('check_In', models.DateField()),
                ('check_Out', models.DateField()),
                ('total_cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('contact_no', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reserve_Room',
            fields=[
                ('room_type', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('credit_card', models.IntegerField()),
                ('debit_card', models.IntegerField()),
                ('check_In', models.DateField()),
                ('check_Out', models.DateField()),
                ('room_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelbooking.Check_Availability')),
            ],
        ),
        migrations.AddField(
            model_name='display',
            name='room_no',
            field=models.ForeignKey(on_delete=True, to='hotelbooking.Reserve_Room'),
        ),
        migrations.AddField(
            model_name='cancle_room',
            name='room_no',
            field=models.ForeignKey(on_delete=True, to='hotelbooking.Display'),
        ),
    ]
