# Generated by Django 2.1.3 on 2018-11-27 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0002_auto_20181127_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('bsdate', models.DateField()),
                ('b_daysno', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking_has',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelbooking.Booking')),
            ],
        ),
        migrations.CreateModel(
            name='Cust_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='', max_length=50)),
                ('lname', models.CharField(default='', max_length=50)),
                ('add', models.CharField(default='', max_length=500)),
                ('email', models.CharField(max_length=100)),
                ('country', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('title', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Room_types',
            fields=[
                ('rt_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('room_type', models.CharField(max_length=50)),
                ('maxno', models.CharField(max_length=10)),
                ('b_price', models.CharField(max_length=10)),
                ('area', models.CharField(max_length=10)),
                ('bed_no', models.CharField(max_length=10)),
                ('quantity', models.CharField(max_length=10)),
                ('boat', models.CharField(max_length=10)),
                ('parking', models.CharField(max_length=10)),
                ('library', models.CharField(max_length=10)),
                ('cinema', models.CharField(max_length=10)),
                ('plift', models.CharField(max_length=10)),
                ('image', models.CharField(max_length=100)),
                ('bld', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('r_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('floor', models.CharField(max_length=10)),
                ('rt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelbooking.Room_types')),
            ],
        ),
        migrations.RemoveField(
            model_name='cancle_room',
            name='room_no',
        ),
        migrations.RemoveField(
            model_name='display',
            name='room_no',
        ),
        migrations.DeleteModel(
            name='Register',
        ),
        migrations.RemoveField(
            model_name='reserve_room',
            name='room_no',
        ),
        migrations.DeleteModel(
            name='Cancle_Room',
        ),
        migrations.DeleteModel(
            name='Check_Availability',
        ),
        migrations.DeleteModel(
            name='Display',
        ),
        migrations.DeleteModel(
            name='Reserve_Room',
        ),
        migrations.AddField(
            model_name='booking_has',
            name='c_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelbooking.Cust_info'),
        ),
        migrations.AddField(
            model_name='booking_has',
            name='r_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelbooking.Rooms'),
        ),
        migrations.AlterUniqueTogether(
            name='booking_has',
            unique_together={('b_id', 'r_id', 'c_id')},
        ),
    ]
