# Generated by Django 2.1.3 on 2018-11-27 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0003_auto_20181127_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancle_Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('cust_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Check_Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.IntegerField()),
                ('maxno', models.CharField(max_length=10)),
                ('check_In', models.DateField()),
                ('check_Out', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Display',
            fields=[
                ('user_name', models.CharField(max_length=50)),
                ('cust_id', models.IntegerField()),
                ('room_type', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('check_In', models.DateField()),
                ('check_Out', models.DateField()),
                ('total_cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('contact_no', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reserve_Room',
            fields=[
                ('room_no', models.IntegerField(max_length=50, primary_key=True, serialize=False)),
                ('credit_card', models.IntegerField()),
                ('debit_card', models.IntegerField()),
                ('check_In', models.DateField()),
                ('check_Out', models.DateField()),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelbooking.Check_Availability')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='booking_has',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='booking_has',
            name='b_id',
        ),
        migrations.RemoveField(
            model_name='booking_has',
            name='c_id',
        ),
        migrations.RemoveField(
            model_name='booking_has',
            name='r_id',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='rt_id',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Booking_has',
        ),
        migrations.DeleteModel(
            name='Cust_info',
        ),
        migrations.DeleteModel(
            name='Room_types',
        ),
        migrations.DeleteModel(
            name='Rooms',
        ),
        migrations.AddField(
            model_name='display',
            name='room_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelbooking.Reserve_Room'),
        ),
        migrations.AddField(
            model_name='cancle_room',
            name='room_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelbooking.Display'),
        ),
    ]
