# Generated by Django 2.1.3 on 2018-11-29 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0004_auto_20181127_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=20)),
                ('contact_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelbooking.Hotels')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=50)),
                ('max_numbers', models.IntegerField()),
                ('bed_option', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('total_rooms', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelbooking.Hotels')),
            ],
        ),
        migrations.RemoveField(
            model_name='cancle_room',
            name='room_no',
        ),
        migrations.RemoveField(
            model_name='display',
            name='room_no',
        ),
        migrations.DeleteModel(
            name='Register',
        ),
        migrations.RemoveField(
            model_name='reserve_room',
            name='room_type',
        ),
        migrations.DeleteModel(
            name='Cancle_Room',
        ),
        migrations.DeleteModel(
            name='Check_Availability',
        ),
        migrations.DeleteModel(
            name='Display',
        ),
        migrations.DeleteModel(
            name='Reserve_Room',
        ),
    ]
