# Generated by Django 2.1.3 on 2018-12-03 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0005_auto_20181129_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check_Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxno', models.CharField(max_length=10)),
                ('check_In', models.DateField()),
                ('check_Out', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='review',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='room',
            name='hotel',
        ),
        migrations.DeleteModel(
            name='Hotels',
        ),
        migrations.AddField(
            model_name='check_availability',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelbooking.Room'),
        ),
    ]
