# Generated by Django 2.1.3 on 2018-12-04 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelbooking', '0006_auto_20181203_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('rpassword', models.CharField(max_length=50)),
                ('contact_no', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
